[profile.default]
src = "src"
out = "out"
libs = ["lib"]
script = "script"

solc_version = "0.8.27"
optimizer = true
optimizer_runs = 200

gas_reports = ["*"]
evm_version = "cancun"

[fuzz]
runs = 256
